### ISSUE TITLE
document how to map a directory to the docker container?

### ISSUE THREAD

**Issue by davew16** [eclipse/openj9-website#13]
This suggestion assumes that there will be people who want to build the openj9-openjdk-jdk9 binaries themselves, but they are not already familiar with docker.

If such people exist they will follow the instructions in the OpenJ9 Build README and successfully build the OpenJ9 binaries in the docker container. However, the instructions don't include mapping a host directory into the docker container, so they won't be able to copy the binaries into a more permanent location.

I suggest changing the README file as follows:

change the "docker run -it openj9" instruction to something like "docker run -v <target_directory_path>:/root/hostdir -it openj9"
after all the instructions to perform the build and run ./bin/java -version, add an instruction to copy the binaries to /root/hostdir so that they will still exist after you exit the docker container.

**Comment by SueChaplain** [comment]
Sounds like a sensible suggestion. @mstoodle - what do you think? 
Sample write up below .... not sure I got all the terminology between files/images/containers in the right place. If you think we should go ahead with this I can update the page on the staging server for someone to test and verify.


- In prepare section, underneath the Dockerfile links
-
Save the Dockerfile to your current directory and run the following command to build a Docker image: 
> docker build -t openj9 -f Dockerfile .

Next, start a Docker Container with the following command:
> docker run -v <host_directory>:/root/hostdir -it openj9
where -v maps any directory, <host_directory>, on your local system to the container /root/hostdir directory so that you can store the binaries, once they are built.
-
-
- In Test section, after java -version
-
Copy the binaries to the container /root/hostdir to store them on your local system.

**Comment by SueChaplain** [comment]
@mstoodle  - Hi Mark, when you come up for air, please can you take a look at this recommendation from Dave and the proposed updates in my comment and let me know if you are happy.

**Comment by DanHeidinga** [comment]
`docker build -t openj9 -f Dockerfile .`

The `-f Dockerfile` is redundant as the Docker will read a file with that name by default.

`Docker Container`. --> container can have a lowercase c.

This really moves in the direction of turning the Dockerfile into a development environment.  (This is basically how I use it but...)

If we're going to go this far, then should we provide a full step-by-step process for building?

**Comment by mstoodle** [comment]
I want first time visitors to have a simple, more or less fool-proof mechanism to build OpenJDK with OpenJ9. So long as there is a clear, minimal set of directions for first timers trying out building OpenJDK with OpenJ9 so that they can very clearly see that it's no different than building OpenJDK with any other JVM, then I'm ok.

I do think we should be more up front that these landing page directions are simply the minimal directions to build and that we are not recommending every person on the planet build OpenJDK with OpenJ9 using precisely those directions. If we're more clear about that, then I expect most people will happily go figure out what else they need to configure in the docker container or to use the recipe in the docker container to configure their own system.

What I really don't want to see is embedded "if you want to do this, then..." paragaphs strewn throughout the directions. My suggestion is that we keep the landing page build directions very simple, and provide a link at the end to a more detailed page where we can add all the bells and whistle directions for developers and users that want to work with the project.

**Comment by SueChaplain** [comment]
Will make this part of the work for issue #25 
Closing this item.
