### ISSUE TITLE
What test information do we need to keep on the build page

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#139]
@smlambert 

I'd like to revisit what we have for the test section of the build page. It is quite lengthy, describing what tests are available and where. I'm not sure it is 100% accurate any more, and I think it might also be duplicating information held elsewhere.

Please can you take a look: https://www.eclipse.org/openj9/oj9_build.html#version-11:test

Ideally I think we should have just a single verification step for someone who builds an OpenJDK using the docker method to determine that the build was successful. i.e. `java -version` with output. We could then link users to more information about our test set up elsewhere, as we do for users who want to build without docker or on a platform other than Linux. This would make the page simpler, reinforcing the message that building an OpenJDK with OpenJ9 is "easy". If the information does not exist elsewhere I'd be happy to help create it.

**Comment by smlambert** [comment]
Sure there is a lot of test doc (spread across the openj9 and adoptopenjdk projects, as we run testing at both projects, now with some overlap).  Since we started a lot of new tests have been enabled, so it likely needs a revisit.  Looking at the link you provided, there are some things that should get updated/corrected and if you do not wish to keep it on the build page but link off to other doc, then that is fine too.

Should determine what question we are addressing (as I think these have different answers):
1) how do you know your build is sane enough to proceed with local changes/testing?
2) how do you know your local changes are ready to commit (what tests are run against the branch that contains your PR)?
3) how do you know a build is production-ready (what tests are run against release builds)?

**Comment by SueChaplain** [comment]
Thanks @smlambert. Sounds like we should fix any inaccuracies asap and then consider placement.
The build page on the website isn't really the go-to place for someone who is making changes to OpenJ9 and attempting personal builds. It is simply illustrating *how easy it is to build an OpenJDK with OpenJ9*. IMO, this page has to be the simplest and shortest it can be, which is why it documents the *build with docker* approach and avoids the more complicated machine setup. To that end, all I think we really need as a *verification test* is `java -version`.

What we could then add to the foot of this page is a short description aimed at potential contributors and where they should go to learn about how to contribute / how to create and test personal builds. Perhaps we need a `test-instructions/` section in `https://github.com/eclipse/openj9/tree/master/doc` where we have content that covers your 1., 2., 3 and directs people to the tests?

**Comment by smlambert** [comment]
Ensuring the ability to run java -version story sounds reasonable, given who you suspect the audience for this info is.

Having a link or footnote sending people to more information, should they wish they to run testing, is likely all that is required.  OpenJ9 testing doc starts here: https://github.com/eclipse/openj9/blob/master/test/README.md

**Comment by SueChaplain** [comment]
Closing this issue.
Extended test section removed and pointers retained to test doc. See https://github.com/eclipse/openj9-website/pull/157
