### ISSUE TITLE
Moving "Build Your Own" Instructions into Docs

### ISSUE THREAD

**Issue by SeanC1083** [eclipse/openj9-website#155]
![move byo to docs page](https://user-images.githubusercontent.com/41338985/52501126-9b848280-2bad-11e9-973b-9731b082fdcb.jpg)

**Comment by SueChaplain** [comment]
@SeanC1083 - I'll defer to the project leads on this one, as the request to have something on the website was a fundamental part of the initial setup. @mstoodle @DanHeidinga @pshipton 

Note also, that the OpenJ9 user documentation is more a focus on the JVM itself rather than a JDK that contains it, because it can be a component of OpenJDK or other proprietary implementations. So although there are mentions of OpenJDK in the docs, they are deliberately few. 

We have detailed build instructions in the OpenJ9 repo (https://github.com/eclipse/openj9/tree/master/doc/build-instructions), which cover all platforms and are quite verbose. The version on the website was an attempt to show just how easy it was to build on a common developer platform.

**Comment by SeanC1083** [comment]
@mstoodle @DanHeidinga @pshipton Just wanted to reach out to you all to begin the conversation about moving the Build Your Own instructions to the Documents page. Would love to get your feedback, both pros & cons, about this design recommendation.

**Comment by pshipton** [comment]
It is fine with me. The website can just link to the doc.
