### ISSUE TITLE
Design for the OpenJ9 Header & Footer

### ISSUE THREAD

**Issue by SeanC1083** [eclipse/openj9-website#156]
<img width="1378" alt="screen shot 2019-02-11 at 10 16 42 am" src="https://user-images.githubusercontent.com/41338985/52572614-32d41a80-2de6-11e9-9bff-5157c1155ec8.png">

**Comment by SeanC1083** [comment]
@SueChaplain Just wanted to begin socializing this new design we've been iterating on for the site's footer.

**Comment by SeanC1083** [comment]
Header Nav Bar will be added to this ticket soon.

**Comment by SueChaplain** [comment]
Hi @SeanC1083 - nice clean look and feel. Couple of comments:

1. The following links are required for project footers, which it looks like you've complied with:

- Main Eclipse Foundation website (http://www.eclipse.org);
- Privacy policy (http://www.eclipse.org/legal/privacy.php);
- Website terms of use (http://www.eclipse.org/legal/termsofuse.php);
- Copyright agent (http://www.eclipse.org/legal/copyright.php); and
- Legal (http://www.eclipse.org/legal).

The only problem I see here is that you have replaced the *OpenJ9 is an Eclipse Incubator project* with the words *OpenJ9 is an Eclipse Foundation project*, presumably to get that 5th vital link in there to the Eclipse Foundation. However, we are required to tell people that OpenJ9 is an "incubator" project, so I think we are back to putting 5 links in the bottom instead of 4 and keeping the original statement?

2. Colours

Something we've talked about a bit before with the home page design. There is a common cookie consent form that all projects are required to use. If you go to our current website, you'll find it will pop up when you hover over the black box that nudges up into the bottom of the screen. That cookie pop up is black/orange, matching the Eclipse Foundation colours. This is one of the reasons we opted for the black/orange pages and I'm not sure if the pop up will work with your current colours. You probably have some ideas here.

**Comment by SeanC1083** [comment]
Thanks for the feedback @SueChaplain.

**Comment by SueChaplain** [comment]
Final design:

![header](https://user-images.githubusercontent.com/18395037/66747344-368bd580-ee7c-11e9-9a3b-aae76f5805b9.png)
![footer](https://user-images.githubusercontent.com/18395037/66747353-3ab7f300-ee7c-11e9-93dd-7a588fb019f8.png)
