### ISSUE TITLE
Add performance charts to the website

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#20]
Add AcmeAir performance charts to the website and connect to a detailed report in the repository.

**Comment by jonathanwoodford** [comment]
The draft looks good. I have a few comments, but these should not block going live:
1) The text at the top of the landing page containing "Low memory footprint. Fast startup time..." could be updated to be a link to take you straight to the performance results / charts.

2) In Firefox (it seems fine in other browsers), trying to click on the "DayTrader 3 benchmark testing" link can be a challenge since the chart pops up in front of it.  It is possible to work around this be scrolling the page so that the link is at the very top or bottom of the page.
