### ISSUE TITLE
Performance results on their own page?

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9-website#26]
It would be easier to point people directly to the performance results (since lots of people are interested in that sort of thing :) ) if they were on a separate page.

Then we could just give them an URL, as opposed to "go to the website, then click on this thing to expand the text". I think we should keep the "Learn more" (maybe make that a little more obvious like "Learn more about OpenJ9 performance") where it is, because we have already told some people to go look for it.

**Comment by pmhayward** [comment]
The following URL will now open the "Learn more" section and jump to the top of it:
  [https://www.eclipse.org/openj9/index.html#performance](https://www.eclipse.org/openj9/index.html#performance)
These two URLs link to the two sections within "Learn more":
  [https://www.eclipse.org/openj9/index.html#smaller](https://www.eclipse.org/openj9/index.html#smaller)
  [https://www.eclipse.org/openj9/index.html#smaller](https://www.eclipse.org/openj9/index.html#faster)

**Comment by SueChaplain** [comment]
I also updated the daytrader.md file to read more like an article than a science experiment! I think it now works ok on its own (if linking to it from an external site) as well as the onward link from the website. Marius and Vijay reviewed the words in there, but if you see any changes you want, please let me know. 

https://github.com/eclipse/openj9-website/blob/master/benchmark/daytrader3.md

**Comment by DanHeidinga** [comment]
Is this change live now?  If so, it doesn't work in Safari.

Using my crystal ball, I think we need a "performance" page as a common page that can link to performance experiments like this.  We'll want to be able to find all the perf info from the website but won't want to include all future performance experiments in the "learn more" section.

**Comment by SueChaplain** [comment]
We will investigate Safari. Looking at the stats ~10% of site users are on Safari, so could be worse.
85% are coming in on Chrome, FF & IE - all of which we know are fine.
The remaining 5% are using some browsers I hardly every heard of, but we'll try and get some tests run.

Regarding your crystal ball, yes, I agree. If we are going to continuously run benchmark tests to shout about performance, we should probably have a dedicated place for that on the site where we can display the high level results and summaries, with an MD file detailing the benchmark setup. When we have new results to display we can replace the content, moving the older high level results and summaries into the MD file and link to all "experiments" from the resources page. We probably need to think about a better menu system for the overall site structure with the extra pages (resources and performance).

Note: The resources page we have at the moment has already been updated to link to the Daytrader.md file.

**Comment by SueChaplain** [comment]
@mstoodle and @vijaysun-omr  
We're talking about how best to create a performance page for the site. Can you tell us which links you shared for performance with the JavaOne audience please? If you shared the ones that Peter created we need to make sure that we don't break anyone by moving this content to a new page:

https://www.eclipse.org/openj9/index.html#smaller
https://www.eclipse.org/openj9/index.html#faster

One thought is to lose the Learn more section ... just leave the intro paragraph underneath a button that says "Check out our performance results" (placed in highlighted area shown in the following .png) ... or words to that effect.

![performance_1](https://user-images.githubusercontent.com/18395037/31342306-3f89f9d4-ad04-11e7-93e6-357e06aaf046.PNG)

If we already shared those smaller/faster links, we can leave the learn more section as is and link from the charts to a new performance page, rather than the daytrader3.md file. The new page could contain much of the existing content in the daytrader3.md file, leaving only the system setup/test process in the md file.

If you have a preference or another idea, please comment.

**Comment by DanHeidinga** [comment]
My vote is for a "performance results" page that has short summaries of the perf results along with links to the relevant experiments / full data.

So the new page would summary the daytrader.md results in 3-5 sentences and then link to the existing daytrader.md file.  New perf results can be added in a similar format when they're available.

**Comment by mstoodle** [comment]
My presentation only contains the following link: 

https://github.ibm.com/runtimes/openj9-website/blob/master/benchmark/daytrader3.md
