### ISSUE TITLE
Create latest release page for 0.25.0

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-website#286]
News page update for upcoming release.

**Comment by SueChaplain** [comment]
Early skeleton draft of what's new highlights for 0.25.0

![image](https://user-images.githubusercontent.com/18395037/110505252-e3ac6100-80f5-11eb-9b75-8bf2d38c8253.png)


@vijay - any performance related info for this release?
@pshipton / @DanHeidinga  - I picked just the JEPS and mixedref build to highlight on the site. Any changes required? Any extras?

Thanks

**Comment by DanHeidinga** [comment]
Nothing else jumps out at me in the https://github.com/eclipse/openj9/milestone/25?closed=1 Milestone.  @tajila @pshipton anything else you want to emphasize?

**Comment by pshipton** [comment]
JEP 347 is an OpenJDK developer thing, I don't think it should be listed here.

Nothing in the current list of JEPs is actually related to OpenJ9. 

"JEP 395 Records" is out of preview and has OpenJ9 support.

Since "Support for further JDK 16 JEPs is underway in the OpenJ9 project" implies that everything not listed is incomplete, I think we should add JEPs 393 and 397 to the list since they are supported by OpenJ9 now.

**Comment by pshipton** [comment]
and to complete the list, might as well list JEP 390 too.

**Comment by SueChaplain** [comment]
@pshipton - list 

- [JEP 380](https://openjdk.java.net/jeps/380): Unix-domain socket channels
- [JEP 394](https://openjdk.java.net/jeps/394): Pattern matching for `instanceof`
- [JEP 396](https://openjdk.java.net/jeps/396): Strongly encapsulate JDK internals by default
- [JEP 392](https://openjdk.java.net/jeps/347): Packaging tool
- [JEP 395](https://openjdk.java.net/jeps/395): Records
- [JEP 393](https://openjdk.java.net/jeps/393): Foreign-Memory Access API
- [JEP 397](https://openjdk.java.net/jeps/397): Sealed Classes

Do you want me to remove "Support for further JDK 16 JEPs is underway in the OpenJ9 project"

**Comment by pshipton** [comment]
Pls add 390, remove 393 (I was wrong about that one) and put the list in numerical order.

> Do you want me to remove "Support for further JDK 16 JEPs is underway in the OpenJ9 project"

No, it's true for JEPs 389 and 393.

**Comment by vijaysun-omr** [comment]
There are at least a couple of performance items such as AOT under debug and string related optimizations that have been enabl;ed. I will compose the text a bit later in the day and post.

**Comment by vijaysun-omr** [comment]
I'm providing some performance/JIT related input but I am sure you can edit it further to make it suitable for release page.

- Startup time when the JVM is run in debug mode improved significantly because the JIT can generate AOT compiled code in the OpenJ9 shared classes cache in this mode. In this release the AOT technology in OpenJ9 was enhanced to account for debug constraints and this led to almost 2.5X shorter startup times for users running in debug mode, e.g. Open Liberty in dev mode (https://openliberty.io/blog/2019/10/22/liberty-dev-mode.html)


- AArch64 throughput performance improved by 10-20% due to inlined write barrier support being added on that platform in this release

- Improved String performance by fixing an issue within the JIT compiler that inadvertently disabled a set of String related peephole optimizations for accelerating concatenations in OpenJ9 releases for JDK 11 onward.

- Enhanced serviceability of the JIT compiler through better jitdump diagnostics to deterministically and reliably recompile methods resulting from unhandled exceptions either from the compilation threads or application threads.

**Comment by SueChaplain** [comment]
@vijaysun-omr - are these all applicable to OpenJDK 16 (this release) or would you rather we held these highlights over for 0.26.0?

**Comment by vijaysun-omr** [comment]
The 3rd bullet point (i.e. String related optimization) is not applicable to JDK8 (but applies to JDK11 and higher). The other 3 enhancements are applicable to all releases. As for holding back for 0.26.0 I am fine deferring to you and the project leads' judgement on that, i.e. whatever helps the project the most.

**Comment by pshipton** [comment]
I don't think we should hold them back, but they can be repeated for the next release.
