### ISSUE TITLE
Add Xdump Option Builder tool

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9-website#32]
I've written a javascript tool for building -Xdump options ([IBM internal link](http://hurgsa.ibm.com/~cheesemp/public/OptionBuilders/XdumpBuilder.html)).

The tool greatly simplifies the process of creating -Xdump options compared to trawling through the [-Xdump documentation](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_7.0.0/com.ibm.java.lnx.70.doc/diag/tools/dumpagents_syntax.html).

I hope to write a similar tool for -Xtrace when I have time, although I think -Xtrace would be significantly more complicated.

**Comment by DanHeidinga** [comment]
A big +1 to getting this shared on the OpenJ9 website.  Having played with the internal version it makes it much simpler to craft a complicated -Xdump option.

**Comment by SueChaplain** [comment]
Briefly discussed with Jonathan and Paul.

Very happy to reference this from our resources page, but before we can do so we need to get it contributed and decide where it should live.

- Paul has signed the Eclipse contributor license
- Next step is an AWSOM request (Jonathan can help)
- Needs an addition to the COO (Jonathan)
- Needs contributing somewhere. @DanHeidinga does it make sense to keep it somewhere in the eclipse/openj9 repo?
- Longer term, when we have some user doc available at Eclipse, we might be able to integrate it into the UI.

And one for -Xtrace would be awsome :-)

**Comment by andrewcraik** [comment]
I actually have an equivalent one built in HTML and JavaScript which should integrate more smoothly and doesn't require a download [https://tlbgsa.ibm.com/~ajcraik/public/dumpCmdBuilder.html](IBM Internal Link). Happy to contribute that if you would like that one.

**Comment by DanHeidinga** [comment]
```
Needs contributing somewhere. @DanHeidinga does it make sense to keep it somewhere in the eclipse/openj9 repo?
```

Ideally this would be live on the website.  The website repo is a better home than the OpenJ9 one.

**Comment by SueChaplain** [comment]
I think the correct place for this in the future is with the user documentation, and yes, that would have it's own repo. 

I guess there is process to follow before this can be contributed, so we can revisit where at that point.

@paulcheeseman and @andrewcraik - will you put your heads together on the work you have done to figure out who will contribute, or whether there is a combined solution that you can work together on?

**Comment by paulcheeseman** [comment]
@andrewcraik - I just added the "priority" field that was in your tool but missing from mine. I think it now does pretty much everything yours does, plus a bit more - e.g. error checking and other logic to enable/disable fields depending on which fields are selected, to prevent invalid options being built.

The only other things in your tool that are missing from mine are some options which seem to relate to multi-tenancy (I assume these are defunct now?), and the "attach" request option, which doesn't seem to be documented anywhere but is accepted on the command line - that does that do?

Please have a play with the tool ([link](http://hurgsa.ibm.com/~cheesemp/public/OptionBuilders/XdumpBuilder.html)) and let me know if you find any problems, or if there's anything else that's missing.

**Comment by andrewcraik** [comment]
@paulcheeseman looks good - the error checking is a nice addition. The multi-tenancy stuff id defunct now. The attach request option is to be able to attach a debugger like GDB I believe at the point where the dump will be taken. We'll have to refresh the syntax for that since it might have changed.

Rest of the tool looks great. I think the major difference in the implementation is just that mine builds the UI from a JavaScript object definition rather than being hardcoded so if we wanted to try and generate the option build from the options processing code we could look to do that in the future, but yours looks nicer and the error checking is an improvement over what I have so we can probably start with yours and go from there.

Since this is pure HTML and JavaScript it will integrate nicely into the website. If you want to lead the way on that then I'm all for it.

**Comment by SueChaplain** [comment]
"Since this is pure HTML and JavaScript it will integrate nicely into the website. If you want to lead the way on that then I'm all for it."

The plan is to host user documentation from a separate repo / website, not this one (which is more like our shop window) and that is the correct place for this, alongside the other command line options. Getting the command line option documentation contributed to Eclipse is a work in progress. We can transfer this issue to the repo when it is created.

**Comment by andrewcraik** [comment]
Sounds good - I was just pointing out that the code should integrate nicely into those docs - nice little usability feature.

**Comment by paulcheeseman** [comment]
I've written a similar tool for Xtrace over the last few weeks ([link](http://hurgsa.ibm.com/~cheesemp/public/OptionBuilders/XtraceBuilder.html)). I'll contribute this at the same time as the Xdump tool.

**Comment by SueChaplain** [comment]
The tools are now live on the website, with links available from topics in the user documentation.
I think it would be a good idea to create a blog about these to advertise them to the community.

https://www.eclipse.org/openj9/docs/xdump/#xdump-option-builder
https://www.eclipse.org/openj9/docs/xtrace/#xtrace-option-builder

https://www.eclipse.org/openj9/docs/tool_builder/

@paulcheeseman - please fork the repo for any changes you might want to make going forward.
