### ISSUE TITLE
Website Download Now link points to Java 9 instead of 8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-website#53]
Now that OpenJ9 Java 8 builds are available at AdoptOpenJDK, lets consider making the website `Download Now` link point to the Java 8 build instead of Java 9.

- Java 8 builds contain fewer known problems compared to Java 9 builds
- there are many migration issues to consider when moving to Java 9 which are not present with Java 8

Lets also consider pointing at the nightly builds instead of the so called "Latest Build". The "Latest Build" contains the latest OpenJDK release content, but to date does not contain refreshed OpenJ9 content. The "Latest Build" could be up to 3 months out of date wrt OpenJ9 content, and will contain known problems which have since been resolved. This should change once OpenJ9 starts creating "releases", tagged levels to indicate builds that pass some quality criteria, which can be used to refresh the AdoptOpenJDK "Latest Build".

Even if we decide not to link to Java 8, or to the nightly builds, we can add some explanation of the above to the website.

**Comment by SueChaplain** [comment]
We've been wondering about this too and whether we should wait for Windows to be added to the available platforms (not sure how far off this might be). I'm happy to point to 8 nightly builds whenever everyone is comfortable. I'd certainly prefer that we pointed to builds that contain refreshed OpenJ9 content than add extra explanations to the website.

It's a simple change - this link?
https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9

**Comment by pshipton** [comment]
The suggested link works for me.

**Comment by jonathanwoodford** [comment]
If we point to the latest nightly level, there is a possibility that this could be broken.

It also lowers the importance of ensuring that the main download link contains the latest good build, which I do not believe is good.

I would feel more comfortable with pointing users to this.
https://adoptopenjdk.net/releases.html?variant=openjdk8-openj9

If it is felt that every nightly level is good and better than the previous one, then AdoptOpenJDK.net should be changing the main download now button to contain the latest nightly build.
If not, there needs to be a way to tag the latest best level, which may or may not be the latest nightly build.

**Comment by jonathanwoodford** [comment]
From above - "It also lowers the importance of ensuring that the main download link contains the latest good build, which I do not believe is good."

I'll reword, this can be interpreted in two ways:
"It also lowers the importance of ensuring that the main download link contains the latest good build.  We need to address this main requirement rather than work around it."

**Comment by jonathanwoodford** [comment]
From the perspective of pointing to v8 rather than v9, you have a +1 from me.

**Comment by tellison** [comment]
@jonathanwoodford regarding pointing to nightly vs. release builds.

The process for defining "a release" is somewhat manual at AdoptOpenJDK, in so far as Jenkins will ensure that the build of Eclipse OpenJ9 code builds cleanly and passes the appropriate tests at AdoptOpenJDK before being manually tagged as a "release".

I expect that the release procedure should be a collaborative action, where the Eclipse team nominate a code level as a release candidate, and once the quality is confirmed, we flag it as a release for the download classification.

This would be a good discussion to have on Slack and summarize back in the issue.

**Comment by aprenaud** [comment]
+1

**Comment by mstoodle** [comment]
The current "release" build at AdoptOpenJDK is just the first build we did for each JDK (so the JDK9 one is from mid September). The quality of those builds is no better/worse necessarily than any other nightly build (which has received the same level of testing as that first build Adopt is currently calling a "release").

On the other hand, people have reported problems in that "release" build that we've fixed and have been verified using the "nightly" builds.

My suggestion is to point people at the nightly builds because those have fixes for the problems that people have raised issues for. Plus we don't actually have a "release" yet so it's somewhat disingenuous to highlight some random build as a "release" build (not-for-production-use banner notwithstanding).

**Comment by mstoodle** [comment]
We do not have significant JDK8 testing at the open project at this point, so I would suggest we should keep our links on the JDK9 download, even though the IBMers at the project know that we're doing significant internal testing on both JDK8 and JDK9. Once https://github.com/eclipse/openj9/issues/660 moves further along, then we can reconsider. Thoughts?

**Comment by DanHeidinga** [comment]
I agree with Mark's comment that the JDK8 testing needs to be enabled and visible in the open before we flip the default to JDK8.

Even after the initial release of OpenJ9 (https://projects.eclipse.org/projects/technology.openj9/releases/0.8), we should continue to point at the nightlies as the initial release hasn't defined a particular quality level (yet).

**Comment by tellison** [comment]
I don't wish to hijack this issue regarding updating a website link to discuss how Eclipse OpenJ9 & AdoptOpenJDK releases are defined, but will reiterate the offer above to define that process on Slack and summarize back to the issues.
