### ISSUE TITLE
Dockerfile links point to GitHub wrapped versions of files

### ISSUE THREAD

**Issue by lmaisons** [eclipse/openj9-website#9]
It would be nice if the Dockerfile links at https://www.eclipse.org/openj9/oj9_build.html pointed at the raw Dockerfile so that one could copy + paste the URI directly into a tool like wget.

**Comment by mstoodle** [comment]
how does one reference the raw file, @lmaisons? Can you provide an example for one of the files, please?

**Comment by mstoodle** [comment]
Once we have the URL required, we should change those "platform name" links to the actual wget command to download the appropriate Dockerfile (one less step to perform).

**Comment by DanHeidinga** [comment]
Example raw link: https://raw.githubusercontent.com/eclipse/openj9/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile

for file: https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile

**Comment by mstoodle** [comment]
Thanks @DanHeidinga . So then the full wget command to get the Linux x86_64 Dockerfile would be:

```
wget https://raw.githubusercontent.com/eclipse/openj9/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile
```

...which then flows into the two docker commands quite naturally (because the docker build command assumes the file `Dockerfile` exists).

**Comment by SueChaplain** [comment]
I've been trying to implement this neatly, with difficulty. The raw string is so long that the full <pre>wget https://raw.githubusercontent.com/eclipse/openj9/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile</pre> ends up popping in a scroll bar, even on the widest of displays. This doesn't look too pretty - just ends up making the page look longer than it needs to be. Reducing the font size of this string will make it look out of place with other command line options on the same page. 

I've come up with this as a possible solution, where each list item is a link to the Dockerfile (for normal viewing) but (view raw file) is a link to the raw file that they can "right-click -> copy link -> paste" onto the command line. 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

We'll start by building a Dockerfile. Pick one of the following Dockerfiles for the platform you want to work on:
    
- Linux on 64-bit x86 systems&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        (view raw file)   
- Linux on 64-bit Power systems&nbsp;   (view raw file)
- Linux on 64-bit z Systems&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          (view raw file)

Copy the link to the raw file into the following command:

wget &lt;raw file&gt;

Then run:

docker build -t openj9 -f Dockerfile .
docker run -it openj9

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
@DanHeidinga  @mstoodle - what is your preference? Does it help if I stage some changes somewhere for review? Any other ideas (which may or may not need CSS changes)?

**Comment by DanHeidinga** [comment]
Is it possible to add a "copy to clipboard" icon next to the long command?  Then it doesn't matter that it needs a scroll bar as its easy to copy - just one click.

**Comment by DanHeidinga** [comment]
Actually, add the same button next to each of the commands?  This will make it easy to one button copy the commands when building...

**Comment by SueChaplain** [comment]
I'm attaching previews of the build page with and without the wget <raw file> string so that you can see what the pages might look like.

**With &lt;pre&gt; boxes**
![issue9_preboxes](https://user-images.githubusercontent.com/18395037/31008936-abcede8e-a4fd-11e7-94e6-3f3088a02f11.PNG)

**Without &lt;pre&gt; boxes**
![issue9_nopreboxes](https://user-images.githubusercontent.com/18395037/31009055-18108b24-a4fe-11e7-96bc-d54d22d70420.PNG)

Personally I think the &lt;pre&gt; boxes look a bit ugly, because the string is so long. 
Adding a copy to clipboard icon is possible, and would require some sort of javascript to implement (will require investigation, maybe AWSOM and EclipseCQ). They could be added to either style of page, which I have indicated with the red highlighted square.

In either case I think we need to allow users to "view" the files as well as copying the raw string.

**Comment by DanHeidinga** [comment]
> In either case I think we need to allow users to "view" the files as well as copying the raw string.

+ 1 to that.

I like the first version as it has the command I need to copy/paste to run right there.  If the scrollbars can be hidden unless the user interacts with the preformatted text, that would be perfect.

**Comment by mstoodle** [comment]
I think I agree with Dan on the first one being better and for the same reason.

**Comment by SueChaplain** [comment]
Any concerns with specifying wget for those on distros without it?

**Comment by DanHeidinga** [comment]
`wget` is standard tool.  We need to assume some basic tools are present.

**Comment by DanHeidinga** [comment]
Any update on this?

**Comment by SueChaplain** [comment]
Not much progress due to other priorities. A consideration here is how the "copy to clipboard" is implemented. There are easy javascript packages available, but they don't work on all browsers. It can also be done in HTML5, which not all browsers support. So the trick here is to do something useful that works for everyone.

**Comment by SueChaplain** [comment]
Closing. The new website design does not feature a build page.
